import React from "react";
import Head from "next/head";
import nextPackage from "package.json";

const Home = () => {
  return (
    <div className="h-screen">
      <Head>
        <title>T3-App-Bun</title>
        <meta
          name="description"
          content="Generated by create next app with the bun wrapper"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-full bg-slate-800 flex flex-col text-white">
        <div className="m-auto flex flex-col">
          <h1 className=" font-bold text-3xl">
            Welcome to <a href="https://nextjs.org">T3-App-Bun!</a> v
            {nextPackage.version}
          </h1>

          <p className="mx-auto mt-4">
            Get started by editing{" "}
            <code className="bg-black p-2 rounded-xl">pages/index.tsx</code>
          </p>
        </div>
      </main>
    </div>
  );
};
export default Home;
